FROM python:3.9-slim

WORKDIR /app

# Копируем список зависимостей и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем ваш скрипт (допустим, он называется worker.py)
COPY worker.py .

# Запускаем скрипт
CMD ["python", "worker.py"]
